trigger:
- master

name: Deploy Bicep files

variables:
  azureServiceConnection: 'godspeed'

  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'jgaopipeline0207rg'
  location: 'centralus'
  templateFile: './azuredeploy.bicep'
pool:
  vmImage: $(vmImageName)


steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'bicepPipeline-conn'
    subscriptionId: '9e8db52a-71bc-4871-9007-1117bf304622'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMPipeline-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.bicep'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'