# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'documentationteam'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'
