trigger:
- master

name: Deploy Bicep files

variables:
  azureServiceConnection: 'AzureRmPipeline-conn'

  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'jgaopipeline0623rg'
  location: 'centralus'
  templateFile: './azuredeploy.bicep'
pool:
  vmImage: $(vmImageName)


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    arguments: 
      -Arg1 $(resourceGroupName) `
      -Arg2 $(location) `
      -Arg3 $(templateFile)
    inlineScript: |
      az --version
      az group create --name $1 --location $2
      az deployment group create --resource-group $1 --template-file $3